### ISSUE TITLE
Implement the `update-problem` script

### ISSUE THREAD

**Issue by mottaquikarim** [mottaquikarim/spectacles#8]
User must supply valid (ie: in existence) UUID, something like:

```
$ npm run-script update-problem -uuid=XXX-XXXX-XXXX
```

If UUID is found, open FE with content displayed, ready for updates

**Comment by mmosayed** [comment]
So I finished the update-problem script but here are a few things:

- It script runs with the following command: 
`npm run-script update-problem -uuid 62e2c530-32d7-4b17-835c-b02f8a137a4a`
For some reason using minimist.js it wasn't recognizing the "keys" for the values. So I had to make it work without the "=" after uuid. I'm basically parsing the 2nd object in the arguments array.

- I check to see if the user enters a UUID string or not.
- I check to see if the entered UUID exists in our content structure
- If all is successful, I run the express server and load the user's default browser with the code editor to that specific problem.

Move to completion, once you approve and merge. Thanks
